# Generated by Django 4.1.7 on 2023-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prayers',
            name='name',
        ),
        migrations.AddField(
            model_name='prayers',
            name='email',
            field=models.EmailField(default='ok', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayers',
            name='first_name',
            field=models.CharField(default='go', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayers',
            name='last_name',
            field=models.CharField(default='rt', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prayers',
            name='phone',
            field=models.CharField(default='re', max_length=255),
            preserve_default=False,
        ),
    ]
