# Generated by Django 4.1.7 on 2023-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('pic', models.ImageField(upload_to='pic/')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
