# Generated by Django 4.1.7 on 2023-06-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=255),
        ),
    ]
