# Generated by Django 4.1.7 on 2023-06-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_remove_comment_name_alter_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pic',
            new_name='A_picture_of_daddie',
        ),
    ]
