# Generated by Django 4.1.7 on 2023-06-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_rename_pic_comment_a_picture_of_daddie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='A_picture_of_daddie',
            new_name='A_picture_of_Daddie',
        ),
    ]
